In [1]:
# import httplib2
# import os
from google.oauth2 import service_account
from googleapiclient import discovery
# import pandas as pd

In [16]:
url='https://drive.google.com/file/d/1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS/view?usp=sharing'
file_id=url.split('/')[-2]
dwn_url='https://drive.google.com/uc?id=' + file_id
df_dan_so = pd.read_csv(dwn_url)
print(df.head())

      TenTinhKH  DoanhSo(CoVAT)
11628   Bắc Kạn         1980000
12403   Bắc Kạn        21660000
12404   Bắc Kạn         8340000
18027   Bắc Kạn         1665000
18028   Bắc Kạn               0

In [ ]:
https://drive.google.com/file/d/1mwy3WmRATps0t36_kesuEY8Thbi4XgzW/view?usp=sharing

In [10]:
url='https://drive.google.com/file/d/1mwy3WmRATps0t36_kesuEY8Thbi4XgzW/view?usp=sharing'
file_id=url.split('/')[-2]
dwn_url='https://drive.google.com/uc?id=' + file_id
df_sales = pd.read_csv(dwn_url)
df_sales.columns

C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4,6,53,59) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Index(['MaCongTy/CN', 'CongTy/CN', 'NgayChungTu', 'SoDonDatHang',
       'SoDonTraHang', 'NgayTraHang', 'HoaDon', 'NgayToiHanTT', 'SoHopDong',
       'TrangThai', 'MaKHThue', 'TenKHThue', 'MaSoThue', 'MaKHDMS', 'MaKHCu',
       'TenKhachHang', 'DiaChiKH', 'MaVungBH', 'TenVungBH', 'MaKhuVuc',
       'TenKhuVuc', 'MaTinhKH', 'TenTinhKH', 'MaQuan/HUyen', 'TenQuan/HUyen',
       'Phuong/Xa', 'MaKenhKH', 'TenKenhKH', 'MaKenhPhu', 'TenKenhPhu',
       'MaHCO', 'TenHCO', 'MaPhanLoaiHCO', 'TenPhanLoaiHCO', 'MaPhanHangHCO',
       'TenPhanHangHCO', 'MaSanPham', 'TenSanPhamNB', 'TenSanPhamVietTat',
       'SoLo', 'SoLuong', 'DonGia(CoVAT)', 'DoanhSo(CoVAT)', 'DonGia(ChuaVAT)',
       'DoanhSo(ChuaVAT)', 'NgayDatDon', 'NguoiTaoDon', 'NgayGiaoHang', 'MaNV',
       'TenCVBH', 'MaNVGH', 'NguoiGiaohang', 'TrangThaiGiaoHang', 'SoXuatHang',
       'DonViGiaoHang', 'TenNhaVanChuyen', 'SoXe', 'NguoiChiuTrachNhiemNo',
       'KieuDonHang', 'MaLyDo', 'MaCSBH', 'MaCTKM', 'MaCTTL', ' Mã Sản Phẩm',
       ' Ngành Hàng', 'DanSo'],
      dtype='object')

In [3]:
https://drive.google.com/file/d/15ClbdtRJhqF6bIDNgRLqI1wAytIoPWWR/view?usp=sharing

SyntaxError: invalid syntax (<ipython-input-3-b0f3c28561bf>, line 1)

In [58]:
url_product='https://drive.google.com/file/d/15ClbdtRJhqF6bIDNgRLqI1wAytIoPWWR/view?usp=sharing'
file_id_product=url_product.split('/')[-2]
dwn_url_product='https://drive.google.com/uc?id=' + file_id
df_product = pd.read_csv(dwn_url)

In [60]:
df_product.columns

Index([' Mã Sản Phẩm', ' Tên Sản Phẩm', ' Tên Viết Tắt', ' Tên Xuất Hoá Đơn',
       ' Ngành Hàng', ' Nhãn Hàng', ' Nhóm Sản Phẩm', ' Thuế Suất',
       ' Danh Mục Sản Phẩm', ' Số Visa', ' Ngày Cấp Visa',
       ' Ngày Hết Hạn Visa', ' ĐV Lưu Kho', ' ĐV Mua', ' ĐV Bán',
       ' Giá Bán Gồm VAT', ' Mã NCC', ' Tên NCC', ' Nhà Sản Xuất',
       ' Nhà Phân Phối', ' Điều Kiện Bảo Quản', ' Nhóm Ưu Tiên', ' Chất Lượng',
       ' Hình Thức', ' Thành Phần Công Dụng', ' Kích Cỡ', ' Màu', ' Kiểu Dáng',
       ' Số Hộp/Thùng', ' Quy Cách Đóng Gói', ' Thể Tích ĐV Lưu Kho',
       ' Trọng Lượng ĐV Lưu Kho', ' Rộng ĐV Lưu Kho', ' Cao ĐV Lưu Kho',
       ' Dài ĐV Lưu Kho', ' Đơn Vị SP Theo ĐV Khác', ' Thể Tích ĐV Khác',
       ' Trọng Lượng ĐV Khác', ' Rộng ĐV Khác', ' Cao ĐV Khác', ' Dài ĐV Khác',
       ' SP Có Lot', ' Thời Gian Bắt Đầu SP', ' Thời Gian Kết Thúc SP',
       ' Đơn Vị Tính Chẵn', ' Tên Đơn Vị Tính Chẵn', ' Đơn Vị Tính Lẻ',
       ' Tên Đơn Vị Tính Lẻ', ' Trạng Thái'],
      dtype='object')

In [39]:
df_test1 = df_sales[['MaSanPham','DoanhSo(CoVAT)']]
df_test1.merge(df_product[[' Mã Sản Phẩm',' Ngành Hàng']], how = 'left',left_on='MaSanPham', right_on=' Mã Sản Phẩm',suffixes=('_left', '_right'), validate="m:1")

      MaSanPham  DoanhSo(CoVAT)  Mã Sản Phẩm               Ngành Hàng
0         EH109        32500000        EH109  Kháng sinh - Kháng viêm
1         EH111         7656000        EH111       Tiêu Hoá - Gan Mật
2         EH111        25344000        EH111       Tiêu Hoá - Gan Mật
3         EH113         5217000        EH113                  Nhỏ Mắt
4         EH113        13283000        EH113                  Nhỏ Mắt
...         ...             ...          ...                      ...
41215     OH075          235000        OH075             Sản Phụ Khoa
41216     OH031          684000        OH031                  Nhỏ Mắt
41217     OH031               0        OH031                  Nhỏ Mắt
41218     OH077          414000        OH077             Sản Phụ Khoa
41219     OH078          414000        OH078             Sản Phụ Khoa

[41220 rows x 4 columns]

In [40]:
df_test1

      MaSanPham  DoanhSo(CoVAT)
0         EH109        32500000
1         EH111         7656000
2         EH111        25344000
3         EH113         5217000
4         EH113        13283000
...         ...             ...
41215     OH075          235000
41216     OH031          684000
41217     OH031               0
41218     OH077          414000
41219     OH078          414000

[41220 rows x 2 columns]

In [11]:
df = df_sales[['TenTinhKH','DoanhSo(CoVAT)']]
df = df[df['TenTinhKH'] == 'Bắc Kạn']

In [12]:
df

      TenTinhKH  DoanhSo(CoVAT)
11628   Bắc Kạn         1980000
12403   Bắc Kạn        21660000
12404   Bắc Kạn         8340000
18027   Bắc Kạn         1665000
18028   Bắc Kạn               0

In [18]:
df.merge(df_dan_so, how = 'left',left_on='TenTinhKH', right_on='TenTinhKH',suffixes=('_left', '_right'), validate="m:1")

  TenTinhKH  DoanhSo(CoVAT)  DanSo
0   Bắc Kạn         1980000    NaN
1   Bắc Kạn        21660000    NaN
2   Bắc Kạn         8340000    NaN
3   Bắc Kạn         1665000    NaN
4   Bắc Kạn               0    NaN

In [71]:
df_test

      TenTinhKH  DoanhSo(CoVAT)
0       Đắk Lắk        32500000
1       Đắk Lắk         7656000
2       Đắk Lắk        25344000
3      Lâm Đồng         5217000
4      Lâm Đồng        13283000
...         ...             ...
41215  Trà Vinh          235000
41216  An Giang          684000
41217  An Giang               0
41218  An Giang          414000
41219  An Giang          414000

[41220 rows x 2 columns]

In [9]:
dwn_url

'https://drive.google.com/uc?id=1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS'

In [7]:
file_id

'1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS'

In [33]:
url_dan_so= 'https://drive.google.com/file/d/1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS/view?usp=sharing'
file_id_dan_so=url_dan_so.split('/')[-2]
dwn_url_dan_so='https://drive.google.com/uc?id=' + file_id_dan_so
df_dan_so = pd.read_csv(dwn_url_dan_so)

In [29]:
df_dan_so.head()

           TenTinhKH    DanSo
0           An Giang  1908352
1  Bà Rịa - Vũng Tàu  1148313
2          Bắc Giang  1803950
3          Bắc Kạn   313905
4           Bạc Liêu   907236

In [64]:
url_dan_so

'https://drive.google.com/file/d/1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS/view?usp=sharing'

In [66]:
file_id_dan_so

'1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS'

In [34]:
df_dan_so = df_dan_so[df_dan_so['TenTinhKH'] == 'Bắc Kạn']
df_dan_so.head()

   TenTinhKH   DanSo
3  Bắc Kạn  313905

Series([], Name: TenTinhKH, dtype: object)

In [56]:
url_dan_so='https://drive.google.com/file/d/1bhb_Rh3Kpm8W0le7VY1TFB2soZvfryPS/view?usp=sharing'
file_id_dan_so=url_dan_so.split('/')[-2]
dwn_url_dan_so='https://drive.google.com/uc?id=' + file_id

In [57]:
dwn_url_dan_so

'https://drive.google.com/uc?id=15ClbdtRJhqF6bIDNgRLqI1wAytIoPWWR'

In [50]:
df_dan_so

,Mã Sản Phẩm,Tên Sản Phẩm,Tên Viết Tắt,Tên Xuất Hoá Đơn,Ngành Hàng,Nhãn Hàng,Nhóm Sản Phẩm,Thuế Suất,Danh Mục Sản Phẩm,Số Visa,...,Cao ĐV Khác,Dài ĐV Khác,SP Có Lot,Thời Gian Bắt Đầu SP,Thời Gian Kết Thúc SP,Đơn Vị Tính Chẵn,Tên Đơn Vị Tính Chẵn,Đơn Vị Tính Lẻ,Tên Đơn Vị Tính Lẻ,Trạng Thái
0,CHUACODE,Chưa Code,chuacode,AQUIMA chai,Tiêu Hoá - Gan Mật,Thuốc,AQUIMA,5,Sản Phẩm Bán,NaN,...,0,0,Sản Phẩm Có Lot,01/01/2020,31/12/2021,1,Hộp,20,Gói,Đang Sử Dụng
1,CK-VOUCHER,Voucher mua hàng,NaN,Voucher mua hàng,Hàng Khuyến Mãi Tặng Kèm,Hàng Khuyến Mãi,Hàng Khuyến Mãi,0,Hàng khuyến mãi tặng kèm,NaN,...,0,0,Sản Phẩm Có Lot,31/12/2020,31/12/2021,1,Cái,1,Cái,Đang Sử Dụng
2,DV01,Tài trợ đơn vị cái,NaN,Tài trợ đơn vị cái,Sản Phẩm Dịch Vụ,Sản Phẩm Dịch Vụ,SP Dịch Vụ,10,Sản Phẩm Tài Trợ,NaN,...,0,0,Sản Phẩm Không Lot,02/05/2021,02/05/2029,1,Cái,1,Cái,Đang Sử Dụng
3,DV02,Tài trợ đơn vị hộp,NaN,Tài trợ đơn vị hộp,Sản Phẩm Dịch Vụ,Sản Phẩm Dịch Vụ,SP Dịch Vụ,10,Sản Phẩm Tài Trợ,NaN,...,0,0,Sản Phẩm Không Lot,02/05/2021,02/05/2029,1,Hộp,1,Hộp,Đang Sử Dụng
4,DV03,Tài trợ đơn vị bộ,NaN,Tài trợ đơn vị bộ,Sản Phẩm Dịch Vụ,Sản Phẩm Dịch Vụ,SP Dịch Vụ,10,Sản Phẩm Tài Trợ,NaN,...,0,0,Sản Phẩm Không Lot,02/05/2021,02/05/2029,1,Bộ,1,Bộ,Đang Sử Dụng
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
710,VT04771,Sticker Ferritox,NaN,Sticker Ferritox,Vật Tư Trình Duyệt,Vật Tư Trình Dược,Vật Tư Trình Dược,10,Vật Tư Trình Dược,NaN,...,0,0,Sản Phẩm Có Lot,31/12/2020,31/12/2021,1,Cái,1,Cái,Đang Sử Dụng
711,VT04772,Brochure Shema Topi,NaN,Brochure Shema Topi,Vật Tư Trình Duyệt,Vật Tư Trình Dược,Vật Tư Trình Dược,10,Vật Tư Trình Dược,NaN,...,0,0,Sản Phẩm Có Lot,31/12/2020,31/12/2022,1,Cái,1,Cái,Đang Sử Dụng
712,VT04773,Phiếu khảo sát,NaN,Phiếu khảo sát,Vật Tư Trình Duyệt,Vật Tư Trình Dược,Vật Tư Trình Dược,10,Vật Tư Trình Dược,NaN,...,0,0,Sản Phẩm Có Lot,31/12/2020,31/12/2021,1,Tờ,1,Tờ,Đang Sử Dụng
713,VT04774,Tờ hướng dẫn Mepatyl,NaN,Tờ hướng dẫn Mepatyl,Vật Tư Trình Duyệt,Vật Tư Trình Dược,Vật Tư Trình Dược,10,Vật Tư Trình Dược,NaN,...,0,0,Sản Phẩm Có Lot,31/12/2020,31/12/2021,1,Tờ,1,Tờ,Đang Sử Dụng
714,VTTT01,Sản phẩm tài trợ,NaN,Sản phẩm tài trợ,Sản Phẩm Dịch Vụ,Sản Phẩm Dịch Vụ,SP Dịch Vụ,10,Sản Phẩm Tài Trợ,NaN,...,0,0,Sản Phẩm Không Lot,04/05/2021,04/05/2029,1,Cái,1,Cái,Đang Sử Dụng

In [2]:
import os

In [3]:
scopes = ['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/drive.file']
jsonfile = os.path.join(os.getcwd(),'bigquery1508.json')
credentials = service_account.Credentials.from_service_account_file(jsonfile, scopes = scopes)
service = discovery.build('sheets','v4',credentials = credentials)

In [4]:
spreadsheets_id ='1C443EykulvJwRf19kylZoE8qeA-XQZsPz3o0ioSEW0o'
response = service.spreadsheets().values().get(
    spreadsheetId = spreadsheets_id,
    majorDimension = 'ROWS',
    range = 'capture2106'
).execute()

In [ ]:
import json

In [17]:
worksheetname = 'DATA!'
cellrangeinsert = 'A1'
values = []
value_range_body = {
    'majorDimension':'ROWS',
    'values': values
}

NameError: name 'json' is not defined

In [18]:
spreadsheets_id ='1C443EykulvJwRf19kylZoE8qeA-XQZsPz3o0ioSEW0o'
response = service.spreadsheets().values().append(
    spreadsheetId = spreadsheets_id,
    valueInputOption='USER_ENTERED',
    range=worksheetname+cellrangeinsert,
    body=value_range_body
).execute()

HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1C443EykulvJwRf19kylZoE8qeA-XQZsPz3o0ioSEW0o/values/DATA%21A1:append?valueInputOption=USER_ENTERED&alt=json returned "Invalid JSON payload received. Unknown name "a" at 'data.values[0]': Cannot find field.". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'data.values[0]', 'description': 'Invalid JSON payload received. Unknown name "a" at \'data.values[0]\': Cannot find field.'}]}]">

In [7]:
columns=response['values'][0]
data=[item for item in response['values'][1:]]
df_raw = pd.DataFrame(data,columns=columns)
df_raw

   A     B      C
0  1  1000   vinh
1  2  5000  khanh