In [2]:
import sys
import os
from datetime import datetime
from google.oauth2 import service_account
from googleapiclient import discovery
from googleapiclient.http import MediaFileUpload
from datetime import datetime
import pandas as pd
import numpy as np
import time
import pyodbc
print(os.path.dirname(sys.executable))

d:\data_sale\venv\Scripts

In [2]:
server = '115.165.164.234'
driver = 'SQL Server'
db1 = 'PhaNam_eSales_PRO'
tcon = 'no'
uname = 'duyvq'
pword = '123VanQuangDuy'
cnxn = pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}', 
                      host=server, database=db1, trusted_connection=tcon,
                      user=uname, password=pword)
cursor = cnxn.cursor()

In [3]:
datenow = datetime.now().strftime("%Y%m%d")
param_1 = f"'20161213'"
param_2 = f"'{datenow}'"

In [4]:
query = f"EXEC [pr_AR_TrackingDebtConfirm]  @Fromdate={param_1}, @Todate={param_2}"
start=time.time()
df1 = pd.read_sql(query, cnxn, parse_dates=['DateOfOrder'])
df1.to_csv('doanhthutienmat_data1.csv', index = False)
end=time.time()
duration=end-start
print(duration)
cnxn.close()

20.458582639694214

In [3]:
df1 = pd.read_csv('[pr_AR_TrackingDebtConfirm.csv', dayfirst=True, parse_dates=['Ngày Đơn Hàng'])

In [4]:
df1.head()

,Mã Chi Nhánh/Cty,Tên Chi Nhánh/Cty,Quản Lý MDS,Mã Nhân Viên,Tên Nhân Viên,Vai Trò,Hình Thức Thanh Toán,Hạn Thanh Toán,Ngày Nghiệp Vụ,Mã Đơn Hàng,...,Giao Thành Công (ĐH),Giao Thành Công (Số Tiền),Hủy Hóa Đơn - Trả Hàng (ĐH),Hủy Hóa Đơn - Trả Hàng (Số Tiền),Xác Nhận Thu Nợ (Số Tiền),Lý Do Không Thu Nợ Được,Tạo Bảng Kê (ĐH),Tạo Bảng Kê (Số Tiền),Xác Nhận TT Công Nợ (ĐH),Xác Nhận TT Công Nợ (Số Tiền)
0,MR0001,CÔNG TY CỔ PHẦN DƯỢC PHA NAM,Lương Trịnh Thắng,GH001,NV giao hàng ảo,MDS,TM,Thanh Toán Ngay,19/08/2021,DH082021-05223,...,0,0,0,0,0,NaN,1,1255990,1,1255990
1,MR0001,CÔNG TY CỔ PHẦN DƯỢC PHA NAM,Lương Trịnh Thắng,GH001,NV giao hàng ảo,MDS,TM,Thanh Toán Ngay,20/08/2021,DH082021-05665,...,0,0,0,0,0,NaN,1,1144994,1,1144994
2,MR0001,CÔNG TY CỔ PHẦN DƯỢC PHA NAM,Lâm Mạnh Quyền,MR0025,Phạm Ngọc Trường,LOG,CK,Cho nợ,19/03/2021,DH032021-02378,...,0,0,0,0,0,NaN,0,0,0,0
3,MR0001,CÔNG TY CỔ PHẦN DƯỢC PHA NAM,Lâm Mạnh Quyền,MR0025,Phạm Ngọc Trường,LOG,TM,Cho nợ,08/03/2021,DH032021-03934,...,0,0,0,0,0,NaN,0,0,0,0
4,MR0001,CÔNG TY CỔ PHẦN DƯỢC PHA NAM,Lâm Mạnh Quyền,MR0025,Phạm Ngọc Trường,LOG,TM,Cho nợ,10/03/2021,DH032021-05263,...,0,0,0,0,0,NaN,0,0,0,0

In [5]:
df2 = df1[['Mã Chi Nhánh/Cty', 'Mã Nhân Viên', 'Ngày Nghiệp Vụ', 'Mã Đơn Hàng', 'Mã Khách Hàng', 'Ngày Đơn Hàng']]

In [6]:
df2[df2.duplicated(keep=False)]

,Mã Chi Nhánh/Cty,Mã Nhân Viên,Ngày Nghiệp Vụ,Mã Đơn Hàng,Mã Khách Hàng,Ngày Đơn Hàng
45232,MR0001,MR1975,14/09/2021,DH082021-06443,P0807-0024,2021-08-22
45233,MR0001,MR1975,14/09/2021,DH082021-06443,P0807-0024,2021-08-22
45234,MR0001,MR1975,22/08/2021,DH082021-06443,P0807-0024,2021-08-22
45235,MR0001,MR1975,22/08/2021,DH082021-06443,P0807-0024,2021-08-22
45236,MR0001,MR1975,23/08/2021,DH082021-06443,P0807-0024,2021-08-22
45237,MR0001,MR1975,23/08/2021,DH082021-06443,P0807-0024,2021-08-22
57091,MR0001,MR2526,08/09/2021,DH072021-04119,000855,2021-07-22
57092,MR0001,MR2526,08/09/2021,DH072021-04119,000855,2021-07-22
57093,MR0001,MR2526,22/07/2021,DH072021-04119,000855,2021-07-22
57094,MR0001,MR2526,22/07/2021,DH072021-04119,000855,2021-07-22
151361,MR0015,MR1664,01/10/2021,DH092021-02002,P5106-0265,2021-09-30
151362,MR0015,MR1664,01/10/2021,DH092021-02002,P5106-0265,2021-09-30
151363,MR0015,MR1664,30/09/2021,DH092021-02002,P5106-0265,2021-09-30
151364,MR0015,MR1664,30/09/2021,DH092021-02002,P5106-0265,2021-09-30
151458,MR0015,MR1720,07/05/2021,DH052021-00340,N0652114,2021-05-07
151459,MR0015,MR1720,07/05/2021,DH052021-00340,N0652114,2021-05-07
151460,MR0015,MR1720,10/05/2021,DH052021-00340,N0652114,2021-05-07
151461,MR0015,MR1720,10/05/2021,DH052021-00340,N0652114,2021-05-07
166382,MR0015,MR2497,15/09/2021,DH092021-00708,N06112076,2021-09-15
166383,MR0015,MR2497,15/09/2021,DH092021-00708,N06112076,2021-09-15

In [21]:
df1 = pd.read_csv('name1.csv')
df2 = pd.read_csv('name2.csv')

In [23]:
pd.concat([df1,df2], ignore_index=True).drop_duplicates(keep=False)

  Name  Age
3    D    4
4    E    5
8    F    5

In [10]:
df3.drop_duplicates(keep=False)

   index Name  Age
3      3    D    4
4      4    E    5
8      3    F    5

In [ ]:
cnxn = pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}', 
                      host=server, database=db1, trusted_connection=tcon,
                      user=uname, password=pword)
query = f"EXEC [pr_AR_RawdataTrackingDebtConfirm]  @RPTID=562"
start=time.time()
df2 = pd.read_sql(query, cnxn, parse_dates={"Ngày Đơn Hàng": {"dayfirst": True, "format": "%d-%m-%y"}})
# df2.to_csv('doanhthutienmat_data2.csv', index = False)
end=time.time()
duration=end-start
print(duration)
cnxn.close()
cnxn = pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}', 
                      host=server, database=db1, trusted_connection=tcon,
                      user=uname, password=pword)
query = f"EXEC [pr_AR_RawdataTrackingDebtConfirm]  @RPTID=562"
start=time.time()
df2 = pd.read_sql(query, cnxn, parse_dates={"Ngày Đơn Hàng": {"dayfirst": True, "format": "%d-%m-%y"}})
# df2.to_csv('doanhthutienmat_data2.csv', index = False)
end=time.time()
duration=end-start
print(duration)
cnxn.close()
df1.columns
df1 = pd.read_csv('doanhthutienmat_data1.csv', dayfirst=True, parse_dates=['DateOfOrder', 'DueDate'])
df2.dtypes
df2 = pd.read_csv('doanhthutienmat_data2.csv', dayfirst=True, parse_dates=['Ngày Đơn Hàng', 'Ngày Đến Hạn'])
df1.shape
df2.shape
df1.columns
df1[(df1['BranchID'] == 'MR0001') & (df1['OrderNbr'] == 'DH092021-00921')].to_clipboard()
df1.dtypes
df1a = df1[['BranchID', 'SlsperID', 'OrderDate', 'OrderNbr', 'CustID', 'DateOfOrder','DueDate','PhoneCustInvc']].copy()
df1a.shape
df1a[df1a.duplicated(keep=False)]
df2[(df2['Mã Chi Nhánh/Cty'] == 'MR0001') & (df2['Mã Đơn Hàng'] == 'DH092021-00921')].to_clipboard()
df2a = df2[['Mã Chi Nhánh/Cty', 'Mã Nhân Viên', 'Ngày Nghiệp Vụ', 'Mã Đơn Hàng', 'Mã Khách Hàng', 'Ngày Đơn Hàng', 'Ngày Đến Hạn', 'Số Điện Thoại (KH Thuế)']].copy()
df2a.shape
df2a[(df2a['BranchID'] == 'MR0001') & (df2a['OrderNbr'] == 'DH052021-03123')].to_clipboard()
df2a[df2a.duplicated(keep=False)]
df2a.columns = df1a.columns
pd.concat([df1a,df2a], ignore_index=True).drop_duplicates(keep=False)
pd.concat([df1a,df2a], ignore_index=True).to_csv('checkup.csv')
df3 = pd.read_csv('checkup.csv')
df3.drop_duplicates(keep=False).to_clipboard()
df1b = df1a[['BranchID', 'OrderNbr']].drop_duplicates(keep=False)
df2b = df2a[['BranchID', 'OrderNbr']]
pd.concat([df1b,df2b], ignore_index=True).drop_duplicates(keep=False).to_clipboard()